// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "mobile", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(11)"}},
		{Name: "password", Type: field.TypeString, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "nick_name", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(25)"}},
		{Name: "birthday", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "gender", Type: field.TypeString, Nullable: true, Default: "male", SchemaType: map[string]string{"mysql": "varchar(16)"}},
		{Name: "role", Type: field.TypeInt32, Nullable: true, Default: 1, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "add_time", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime(3)"}},
		{Name: "is_deleted_at", Type: field.TypeInt8, Nullable: true, SchemaType: map[string]string{"mysql": "tinyint(1)"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
