// Code generated by ent, DO NOT EDIT.

package ent

import (
	"user/internal/data/ent/schema"
	"user/internal/data/ent/users"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	usersFields := schema.Users{}.Fields()
	_ = usersFields
	// usersDescGender is the schema descriptor for gender field.
	usersDescGender := usersFields[5].Descriptor()
	// users.DefaultGender holds the default value on creation for the gender field.
	users.DefaultGender = usersDescGender.Default.(string)
	// usersDescRole is the schema descriptor for role field.
	usersDescRole := usersFields[6].Descriptor()
	// users.DefaultRole holds the default value on creation for the role field.
	users.DefaultRole = usersDescRole.Default.(int32)
}
